// =============================================================================
// TEAMTOWERS SOS V11 — I18N
// Ruta: /js/i18n.js
//
// Uso:
//   import { t, setLang, getLang } from '../i18n.js';
//   t('dashboard.title')  → 'Value Map Dashboard' | 'Panel de Mapas de Valor'
//
// Idioma por defecto: 'en'. Persiste en KB como 'sos_lang'.
// Para cambiar: setLang('es') — recarga la vista activa automáticamente.
// =============================================================================

const STRINGS = {

    en: {
        // ── App shell ──────────────────────────────────────────────────────
        'app.name':           'TeamTowers',
        'app.version':        'SOS V11',
        'app.back':           '← Home',
        'app.settings':       'Settings',
        'app.save':           'Save',
        'app.saving':         'Saving…',
        'app.saved':          'Saved',
        'app.error':          'Error',
        'app.cancel':         'Cancel',
        'app.confirm':        'Confirm',
        'app.delete':         'Delete',
        'app.edit':           'Edit',
        'app.add':            'Add',
        'app.close':          'Close',
        'app.loading':        'Loading…',

        // ── Dashboard ──────────────────────────────────────────────────────
        'dash.title':         'Value Map Dashboard',
        'dash.new':           '+ New Project',
        'dash.kb':            'Knowledge Base',
        'dash.settings':      'Settings',
        'dash.stat.projects': 'Projects',
        'dash.stat.roles':    'Total roles',
        'dash.stat.txs':      'Transactions',
        'dash.empty.title':   'No value maps yet.',
        'dash.empty.sub':     'Click "+ New Project" to start.',
        'dash.card.roles':    'roles',
        'dash.card.txs':      'transactions',
        'dash.card.health':   'health',
        'dash.card.empty':    'empty',
        'dash.card.archive':  'Archive',
        'dash.card.new':      'New project',
        'dash.group.general': 'General',
        'dash.hero.sub.empty':'No projects yet — create your first value map',
        'dash.hero.sub.many': 'active projects · ordered by sector',
        'dash.hero.sub.one':  'active project',

        // Modal new project
        'dash.modal.title':   'New project',
        'dash.modal.sub':     'Create a new value network map',
        'dash.modal.name':    'Project name *',
        'dash.modal.name.ph': 'e.g. ACME Corp · VNA 2025',
        'dash.modal.sector':  'Sector (optional)',
        'dash.modal.sector.ph':'— Select sector —',
        'dash.modal.create':  'Create & open map',

        // KB panel
        'dash.kb.title':      'Knowledge Base',
        'dash.kb.hint':       'Click a sector to preview its roles',
        'dash.kb.ready':      'ready',
        'dash.kb.tier2':      'tier 2',
        'dash.kb.tier2.msg':  'Sector not loaded yet — will be generated by AI when needed.',
        'dash.kb.txs':        'Key transactions',
        'dash.kb.more':       'more transactions',

        // ── ValueMapView ───────────────────────────────────────────────────
        'vmap.title':         'Value Map',
        'vmap.no.project':    'No project',
        'vmap.fit':           'Fit',
        'vmap.reset':         'Reorganize',
        'vmap.save':          'Save',
        'vmap.suggest':       '✦ Suggest with AI',
        'vmap.roles':         'Roles',
        'vmap.transactions':  'Transactions',
        'vmap.new.role':      '+ New role',
        'vmap.new.tx':        '+ New transaction',

        // Selector de modo
        'vmap.mode.title':    'New value map',
        'vmap.mode.sub':      'How do you want to start?',
        'vmap.mode.blank':    'From scratch',
        'vmap.mode.blank.desc':'Empty canvas. Draw each role and transaction manually.',
        'vmap.mode.sector':   'From sector',
        'vmap.mode.sector.desc':'Load typical roles and transactions for your sector.',
        'vmap.mode.sector.ph':'Choose sector…',

        // Toolbar
        'vmap.zoom.in':       'Zoom in',
        'vmap.zoom.out':      'Zoom out',
        'vmap.undo':          'Undo',
        'vmap.redo':          'Redo',
        'vmap.legend':        'Legend',

        // Niveles castelleros
        'level.pinya':        'Base layer',
        'level.tronc':        'Value core',
        'level.pom':          'Strategic apex',
        'level.pinya.tip':    'pinya — the foundation that holds everything',
        'level.tronc.tip':    'tronc — where value is generated and transformed',
        'level.pom.tip':      'pom de dalt — sets direction and receives outcomes',

        // Inspector
        'insp.empty':         'Select a role\nor transaction\nto see its detail',
        'insp.level':         'Level',
        'insp.desc':          'Description',
        'insp.actor':         'Typical actor',
        'insp.txs':           'Transactions',
        'insp.tx.in':         'incoming',
        'insp.tx.out':        'outgoing',
        'insp.incomplete':    'Incomplete flow — add transactions',
        'insp.type':          'Type',
        'insp.flow':          'Flow',
        'insp.hint':          'Health signal',
        'insp.ego':           '◎ Ego view',
        'insp.add.tx':        '+ Add transaction',
        'insp.del.role':      '✕ Remove role',
        'insp.edit.tx':       '✏ Edit transaction',
        'insp.del.tx':        '✕ Remove',
        'insp.health.ok':     'Healthy',
        'insp.health.warn':   'Attention',
        'insp.health.crit':   'Critical',

        // Modal rol
        'role.modal.new':     'New role',
        'role.modal.edit':    'Edit role',
        'role.modal.sub':     'Define the activity as part of the value flow',
        'role.modal.name':    'Activity name *',
        'role.modal.name.ph': 'e.g. Demand generator',
        'role.modal.level':   'Level',
        'role.modal.desc':    'Description (optional)',
        'role.modal.desc.ph': 'What does this role do in the value flow?',
        'role.modal.actor':   'Typical actor (optional)',
        'role.modal.actor.ph':'e.g. commercial director, client, ops',
        'role.modal.add':     'Add to map',
        'role.modal.save':    'Save',

        // Modal tx
        'tx.modal.new':       'New transaction',
        'tx.modal.edit':      'Edit transaction',
        'tx.modal.sub':       'Define the deliverable that flows between two roles',
        'tx.modal.deliv':     'Deliverable *',
        'tx.modal.deliv.ph':  'e.g. Economic proposal, Client feedback',
        'tx.modal.from':      'From (origin) *',
        'tx.modal.to':        'To (destination) *',
        'tx.modal.type':      'Type',
        'tx.modal.tangible':  'Tangible (contractual)',
        'tx.modal.intangible':'Intangible (informal)',
        'tx.modal.nature':    'Nature',
        'tx.modal.must':      'MUST (expected)',
        'tx.modal.extra':     'EXTRA (voluntary)',
        'tx.modal.hint':      'Health signal (optional)',
        'tx.modal.hint.ph':   'What happens if this transaction fails?',
        'tx.modal.add':       'Add to map',
        'tx.modal.save':      'Save',

        // Ego mode
        'ego.banner':         'Ego view:',
        'ego.back':           '← Full network',

        // AI panel
        'ai.panel.title':     'Suggest with AI',
        'ai.prompt.label':    'Describe the organization',
        'ai.prompt.ph':       'e.g. 15-person consultancy specializing in digital transformation for industrial SMEs. Technical team, commercial team and freelance partner network…',
        'ai.tips.title':      '✦ Antigravity prompt tips',
        'ai.tip.1':           'Be specific about sector and size: "8-specialist private clinic" beats "healthcare company"',
        'ai.tip.2':           'Name the real actors: clients, suppliers, partners, internal teams',
        'ai.tip.3':           'Mention the goal: "reduce onboarding time" gives strategic context',
        'ai.tip.4':           'Include what works well and what doesn\'t: AI will prioritize broken intangibles',
        'ai.tip.5':           'Don\'t explain VNA — describe operational reality and let the AI map the flows',
        'ai.generate':        '✦ Generate value map',
        'ai.completing':      'Completing the map…',
        'ai.generating':      'Generating value map…',
        'ai.enriching':       'Enriching context with knowledge base…',
        'ai.calling':         'Calling Anthropic…',
        'ai.processing':      'Processing response…',
        'ai.no.key':          'No API Key — configure in Settings',
        'ai.no.results':      'AI returned no proposals. Try with more context.',
        'ai.retry':           '↺ Regenerate',
        'ai.bulk':            '✓ Accept all pending',
        'ai.accept':          '✓ Accept',
        'ai.edit':            '✏ Edit',
        'ai.reject':          '✕',
        'ai.roles.title':     'Suggested roles',
        'ai.txs.title':       'Suggested transactions',
        'ai.roles.2min':      'You need at least 2 roles to create a transaction.',

        // Legend
        'legend.title':       'Map legend',
        'legend.tangible':    'Solid green = Tangible transaction (contractual, MUST)',
        'legend.intangible':  'Gold dashed = Intangible transaction (informal, EXTRA)',
        'legend.levels':      'Role level colours:',
        'legend.pinya':       'Blue = Base layer (pinya)',
        'legend.tronc':       'Indigo = Value core (tronc)',
        'legend.pom':         'Purple = Strategic apex (pom de dalt)',

        // Save
        'save.saving':        'Saving…',
        'save.ok':            'Saved',
        'save.error':         'Error',

        // Settings
        'settings.title':     'Settings · Vault',
        'settings.sub':       'API Keys · AI Engine · IndexedDB (zero localStorage)',
        'settings.engine':    'Primary engine',
        'settings.key.ant':   'Anthropic API Key',
        'settings.key.ant.hint':'(primary · via Netlify proxy)',
        'settings.save':      'Save to KB',
        'settings.saving':    'Saving…',
        'settings.saved':     'Saved',
        'settings.danger':    'Danger zone',
        'settings.purge':     'Purge IndexedDB',
        'settings.purge.confirm': 'Purge all IndexedDB? This deletes API Keys and state.',
        'settings.purged':    'Purged. Reloading…',
        'settings.back':      '← Home',
        'settings.lang':      'Language',
    },

    es: {
        // ── App shell ──────────────────────────────────────────────────────
        'app.name':           'TeamTowers',
        'app.version':        'SOS V11',
        'app.back':           '← Inicio',
        'app.settings':       'Ajustes',
        'app.save':           'Guardar',
        'app.saving':         'Guardando…',
        'app.saved':          'Guardado',
        'app.error':          'Error',
        'app.cancel':         'Cancelar',
        'app.confirm':        'Confirmar',
        'app.delete':         'Eliminar',
        'app.edit':           'Editar',
        'app.add':            'Añadir',
        'app.close':          'Cerrar',
        'app.loading':        'Cargando…',

        // ── Dashboard ──────────────────────────────────────────────────────
        'dash.title':         'Panel de Mapas de Valor',
        'dash.new':           '+ Nuevo Proyecto',
        'dash.kb':            'Base de Conocimiento',
        'dash.settings':      'Ajustes',
        'dash.stat.projects': 'Proyectos',
        'dash.stat.roles':    'Roles totales',
        'dash.stat.txs':      'Transacciones',
        'dash.empty.title':   'Sin mapas de valor todavía.',
        'dash.empty.sub':     'Pulsa "+ Nuevo Proyecto" para empezar.',
        'dash.card.roles':    'roles',
        'dash.card.txs':      'transacciones',
        'dash.card.health':   'salud',
        'dash.card.empty':    'vacío',
        'dash.card.archive':  'Archivar',
        'dash.card.new':      'Nuevo proyecto',
        'dash.group.general': 'General',
        'dash.hero.sub.empty':'Sin proyectos — crea tu primer mapa de valor',
        'dash.hero.sub.many': 'proyectos activos · ordenados por sector',
        'dash.hero.sub.one':  'proyecto activo',

        'dash.modal.title':   'Nuevo proyecto',
        'dash.modal.sub':     'Crea un nuevo mapa de red de valor',
        'dash.modal.name':    'Nombre del proyecto *',
        'dash.modal.name.ph': 'ej. ACME Corp · VNA 2025',
        'dash.modal.sector':  'Sector (opcional)',
        'dash.modal.sector.ph':'— Elige sector —',
        'dash.modal.create':  'Crear y abrir mapa',

        'dash.kb.title':      'Base de Conocimiento',
        'dash.kb.hint':       'Haz click en un sector para ver sus roles',
        'dash.kb.ready':      'listo',
        'dash.kb.tier2':      'tier 2',
        'dash.kb.tier2.msg':  'Sector no cargado — se generará con IA cuando sea necesario.',
        'dash.kb.txs':        'Transacciones clave',
        'dash.kb.more':       'transacciones más',

        // ── ValueMapView ───────────────────────────────────────────────────
        'vmap.title':         'Mapa de Valor',
        'vmap.no.project':    'Sin proyecto',
        'vmap.fit':           'Ajustar',
        'vmap.reset':         'Reorganizar',
        'vmap.save':          'Guardar',
        'vmap.suggest':       '✦ Sugerir con IA',
        'vmap.roles':         'Roles',
        'vmap.transactions':  'Transacciones',
        'vmap.new.role':      '+ Nuevo rol',
        'vmap.new.tx':        '+ Nueva transacción',

        'vmap.mode.title':    'Nuevo mapa de valor',
        'vmap.mode.sub':      '¿Cómo quieres empezar?',
        'vmap.mode.blank':    'Desde cero',
        'vmap.mode.blank.desc':'Canvas vacío. Dibuja cada rol y transacción manualmente.',
        'vmap.mode.sector':   'Desde sector',
        'vmap.mode.sector.desc':'Carga roles y transacciones típicos del sector como punto de partida.',
        'vmap.mode.sector.ph':'Elige sector…',

        'vmap.zoom.in':       'Zoom +',
        'vmap.zoom.out':      'Zoom -',
        'vmap.undo':          'Deshacer',
        'vmap.redo':          'Rehacer',
        'vmap.legend':        'Leyenda',

        'level.pinya':        'Base operativa',
        'level.tronc':        'Núcleo de valor',
        'level.pom':          'Cúspide estratégica',
        'level.pinya.tip':    'pinya — el cimiento que sostiene todo',
        'level.tronc.tip':    'tronc — donde se genera y transforma el valor',
        'level.pom.tip':      'pom de dalt — quien define el rumbo y recibe el resultado',

        'insp.empty':         'Selecciona un rol\no transacción\npara ver su detalle',
        'insp.level':         'Nivel',
        'insp.desc':          'Descripción',
        'insp.actor':         'Actor típico',
        'insp.txs':           'Transacciones',
        'insp.tx.in':         'entrantes',
        'insp.tx.out':        'salientes',
        'insp.incomplete':    'Flujo incompleto — añade transacciones',
        'insp.type':          'Tipo',
        'insp.flow':          'Flujo',
        'insp.hint':          'Señal de alerta',
        'insp.ego':           '◎ Vista ego',
        'insp.add.tx':        '+ Añadir transacción',
        'insp.del.role':      '✕ Eliminar rol',
        'insp.edit.tx':       '✏ Editar transacción',
        'insp.del.tx':        '✕ Eliminar',
        'insp.health.ok':     'Saludable',
        'insp.health.warn':   'Atención',
        'insp.health.crit':   'Crítico',

        'role.modal.new':     'Nuevo rol',
        'role.modal.edit':    'Editar rol',
        'role.modal.sub':     'Define la actividad como parte del flujo de valor',
        'role.modal.name':    'Nombre de la actividad *',
        'role.modal.name.ph': 'ej: Generador de demanda',
        'role.modal.level':   'Nivel',
        'role.modal.desc':    'Descripción (opcional)',
        'role.modal.desc.ph': '¿Qué hace este rol en el flujo de valor?',
        'role.modal.actor':   'Actor típico (opcional)',
        'role.modal.actor.ph':'ej: director comercial, cliente, ops',
        'role.modal.add':     'Añadir al mapa',
        'role.modal.save':    'Guardar',

        'tx.modal.new':       'Nueva transacción',
        'tx.modal.edit':      'Editar transacción',
        'tx.modal.sub':       'Define el entregable que fluye entre dos roles',
        'tx.modal.deliv':     'Entregable *',
        'tx.modal.deliv.ph':  'ej: Propuesta económica, Feedback del cliente',
        'tx.modal.from':      'De (origen) *',
        'tx.modal.to':        'A (destino) *',
        'tx.modal.type':      'Tipo',
        'tx.modal.tangible':  'Tangible (contractual)',
        'tx.modal.intangible':'Intangible (informal)',
        'tx.modal.nature':    'Naturaleza',
        'tx.modal.must':      'MUST (esperado)',
        'tx.modal.extra':     'EXTRA (voluntario)',
        'tx.modal.hint':      'Señal de alerta (opcional)',
        'tx.modal.hint.ph':   '¿Qué pasa si esta transacción falla?',
        'tx.modal.add':       'Añadir al mapa',
        'tx.modal.save':      'Guardar',

        'ego.banner':         'Vista ego:',
        'ego.back':           '← Ver red completa',

        'ai.panel.title':     'Sugerir con IA',
        'ai.prompt.label':    'Describe la organización',
        'ai.prompt.ph':       'ej: Consultora de 15 personas especializada en transformación digital para pymes industriales…',
        'ai.tips.title':      '✦ Antigravity prompt tips',
        'ai.tip.1':           'Sé específico sobre el sector y tamaño: "clínica privada de 8 especialistas" mejor que "empresa de salud"',
        'ai.tip.2':           'Nombra los actores clave reales: clientes, proveedores, socios, equipos internos',
        'ai.tip.3':           'Menciona el objetivo: "reducir tiempo de onboarding" da contexto estratégico',
        'ai.tip.4':           'Incluye lo que funciona bien y lo que no: la IA priorizará los intangibles rotos',
        'ai.tip.5':           'No expliques el VNA — describe la realidad operativa y deja que la IA mapee los flujos',
        'ai.generate':        '✦ Generar mapa de valor',
        'ai.completing':      'Completando el mapa…',
        'ai.generating':      'Generando mapa de valor…',
        'ai.enriching':       'Enriqueciendo contexto con la base de conocimiento…',
        'ai.calling':         'Llamando a Anthropic…',
        'ai.processing':      'Procesando respuesta…',
        'ai.no.key':          'Sin API Key — configura en Ajustes',
        'ai.no.results':      'La IA no devolvió propuestas. Prueba con más contexto.',
        'ai.retry':           '↺ Volver a generar',
        'ai.bulk':            '✓ Aceptar todos los pendientes',
        'ai.accept':          '✓ Aceptar',
        'ai.edit':            '✏ Editar',
        'ai.reject':          '✕',
        'ai.roles.title':     'Roles sugeridos',
        'ai.txs.title':       'Transacciones sugeridas',
        'ai.roles.2min':      'Necesitas al menos 2 roles para crear una transacción.',

        'legend.title':       'Leyenda del mapa',
        'legend.tangible':    'Verde sólido = Transacción tangible (contractual, MUST)',
        'legend.intangible':  'Dorado punteado = Transacción intangible (informal, EXTRA)',
        'legend.levels':      'Colores de nivel de rol:',
        'legend.pinya':       'Azul = Base operativa (pinya)',
        'legend.tronc':       'Índigo = Núcleo de valor (tronc)',
        'legend.pom':         'Púrpura = Cúspide estratégica (pom de dalt)',

        'save.saving':        'Guardando…',
        'save.ok':            '✅ Guardado',
        'save.error':         '❌ Error',

        'settings.title':     'Settings · Bóveda',
        'settings.sub':       'API Keys · Motor IA · IndexedDB (zero localStorage)',
        'settings.engine':    'Motor primario',
        'settings.key.ant':   'Anthropic API Key',
        'settings.key.ant.hint':'(primario · via proxy Netlify)',
        'settings.save':      'Guardar en KB',
        'settings.saving':    'Guardando…',
        'settings.saved':     'Guardado',
        'settings.danger':    'Zona de peligro',
        'settings.purge':     'Purgar IndexedDB',
        'settings.purge.confirm': '¿Purgar toda la IndexedDB? Esto borra API Keys y estado.',
        'settings.purged':    'Purgado. Recargando…',
        'settings.back':      '← Inicio',
        'settings.lang':      'Idioma',
    },
};

// ─── API pública ──────────────────────────────────────────────────────────────

/** Traduce una clave. Si no existe, devuelve la clave como fallback. */
export function t(key) {
    const lang = getLang();
    const dict = STRINGS[lang] || STRINGS['en'];
    return dict[key] !== undefined ? dict[key] : (STRINGS['en'][key] || key);
}

/** Devuelve el idioma activo ('en' | 'es'). */
export function getLang() {
    return window.__lang || 'en';
}

/** Cambia el idioma, persiste en KB y recarga la vista activa. */
export async function setLang(lang) {
    if (lang !== 'en' && lang !== 'es') return;
    window.__lang = lang;

    // Persistir en KB (sin bloquear si KB no está lista)
    try {
        const { KB } = await import('./core/kb.js');
        await KB.init();
        await KB.saveNode({ id: 'sos_lang', type: 'config', value: lang });
    } catch (_) {}

    // Recargar la vista activa para aplicar el idioma
    if (window.navigateTo) {
        window.navigateTo(window.location.pathname + window.location.search);
    } else {
        window.location.reload();
    }
}

/** Inicializa el idioma desde KB al arrancar el sistema. */
export async function initLang() {
    try {
        const { KB } = await import('./core/kb.js');
        await KB.init();
        const node = await KB.getNode('sos_lang');
        window.__lang = (node && node.value) ? node.value : 'en';
    } catch (_) {
        window.__lang = 'en';
    }
}

/** Genera el HTML del selector EN/ES para insertar en cualquier topbar. */
export function langSelectorHtml() {
    const lang = getLang();
    return '<div style="display:flex;gap:2px;background:rgba(0,0,0,0.3);border:1px solid var(--glass-border);border-radius:var(--radius-sm);padding:2px;">' +
        '<button onclick="window.__setLang(\'en\')" style="background:' + (lang === 'en' ? 'var(--accent-indigo)' : 'transparent') + ';border:none;color:' + (lang === 'en' ? 'white' : 'var(--text-muted)') + ';padding:3px 8px;border-radius:3px;cursor:pointer;font-size:10px;font-weight:700;font-family:var(--font-mono);transition:all 0.15s;">EN</button>' +
        '<button onclick="window.__setLang(\'es\')" style="background:' + (lang === 'es' ? 'var(--accent-indigo)' : 'transparent') + ';border:none;color:' + (lang === 'es' ? 'white' : 'var(--text-muted)') + ';padding:3px 8px;border-radius:3px;cursor:pointer;font-size:10px;font-weight:700;font-family:var(--font-mono);transition:all 0.15s;">ES</button>' +
    '</div>';
}
