[build]
  publish = "."

[edge_functions]
  directory = "netlify/edge-functions"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "no-cache, must-revalidate"

[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "no-cache, must-revalidate"

[[edge_functions]]
  path     = "/api/anthropic-proxy"
  function = "anthropic-proxy"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200