// PROJ-QUALITY-001 sprint A · tests stand-alone per projectQualityService.
// Executable a node 18+ · zero deps · zero network.
//
// Ús:
//   node js/tests/projectQuality.test.js

import * as q from '../core/projectQualityService.js';

let pass = 0, fail = 0;
function t(cond, msg) {
    if (cond) { pass++; console.log('✓ ' + msg); }
    else      { fail++; console.error('✘ ' + msg); }
}

// ─── Fixtures ────────────────────────────────────────────────────────────
const emptyProject = { id: 'p-empty', nombre: 'Empty' };

const fullProject = {
    id: 'p-full',
    nombre: 'Full Demo',
    description: 'This is a project description that is long enough to count for the landing check.',
    presentation_narrative_v1: '## Hero\nGenerated by IA.',
    vna_roles: [
        { id: 'r1', name: 'Alpha', typical_actor: 'Sr ops' },
        { id: 'r2', name: 'Beta',  typical_actor: 'Mid IC' },
        { id: 'r3', name: 'Gamma', typical_actor: 'Coord'  },
    ],
    vna_transactions: [
        { id: 'tx-a-b-t',  from: 'r1', to: 'r2', deliverable: 'platform',         type: 'tangible'   },
        { id: 'tx-b-a-t',  from: 'r2', to: 'r1', deliverable: 'weight distrib',   type: 'tangible'   },
        { id: 'tx-a-b-i',  from: 'r1', to: 'r2', deliverable: 'psy sec',          type: 'intangible' },
        { id: 'tx-b-c-t',  from: 'r2', to: 'r3', deliverable: 'shoulder',         type: 'tangible'   },
        { id: 'tx-c-a-t',  from: 'r3', to: 'r1', deliverable: 'feedback',         type: 'tangible'   },
    ],
};

const fullSops = [
    { id: 's1', content: { projectId: 'p-full', roleId: 'r1', body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do.' } },
    { id: 's2', content: { projectId: 'p-full', roleId: 'r2', steps: ['step1', 'step2', 'step3'] } },
    { id: 's3', content: { projectId: 'p-full', roleId: 'r3', body: 'Another body long enough to count as content for the SOP check.' } },
];

const fullWorkshops = [
    { id: 'w1', content: { projectId: 'p-full', audience: 'founders', accessTier: 'public' } },
];

const fullMarket = [
    { id: 'mi1', content: { projectId: 'p-full', title: 'Mentoria 1:1' } },
];

// ─── Tests ───────────────────────────────────────────────────────────────
console.log('\n=== PROJ-QUALITY-001 sprint A · projectQualityService ===\n');

// 1. Exports presents
t(Array.isArray(q.QUALITY_DIMS),                                     'A · QUALITY_DIMS exportat');
t(q.QUALITY_DIMS.length === 5,                                       'A · 5 dimensions');
t(typeof q.computeQualityScore === 'function',                       'A · computeQualityScore exportat');
t(typeof q.statusColor === 'function',                               'A · statusColor exportat');
t(typeof q.statusIcon === 'function',                                'A · statusIcon exportat');

// 2. Pesos sumen 100
const totalWeight = q.QUALITY_DIMS.reduce((a, d) => a + d.weight, 0);
t(totalWeight === 100,                                               'A · pesos sumen 100 (' + totalWeight + ')');

// 3. Tots els dims tenen id+weight+label+icon
const allValid = q.QUALITY_DIMS.every(d => d.id && d.weight && d.label && d.icon);
t(allValid,                                                          'A · cada dim té id+weight+label+icon');

// 4. Llindar high/medium definits
t(q.QUALITY_THRESHOLDS.high === 75,                                  'A · llindar high = 75');
t(q.QUALITY_THRESHOLDS.medium === 50,                                'A · llindar medium = 50');

// 5. Projecte buit · score 0 · status low
const r0 = q.computeQualityScore(emptyProject);
t(r0.total === 0,                                                    'B · projecte buit · total 0');
t(r0.status === 'low',                                               'B · projecte buit · status low');
t(Array.isArray(r0.missing) && r0.missing.length > 0,                'B · projecte buit · missing populated');

// 6. Projecte null · invalid
const rNull = q.computeQualityScore(null);
t(rNull.status === 'invalid',                                        'B · null project · invalid');
t(rNull.total === 0,                                                 'B · null project · total 0');

// 7. Projecte ple · landing 100
const rFull = q.computeQualityScore(fullProject, {
    sops: fullSops, workshops: fullWorkshops, marketItems: fullMarket,
});
t(rFull.byDim.landing.score === 100,                                 'C · landing complet · 100');
t(rFull.byDim.landing.missing.length === 0,                          'C · landing complet · sense missing');

// 8. Value map · 3 roles + 5 tx + intangible + cicle → 100
t(rFull.byDim.valueMap.score === 100,                                'C · value map complet · 100');

// 9. Deliverables · cada role té tx amb deliverable + typical_actor
t(rFull.byDim.deliverables.score === 100,                            'C · deliverables complet · 100');

// 10. SOPs · 3 roles · 3 SOPs amb contingut · 100
t(rFull.byDim.sops.score === 100,                                    'C · SOPs complet · 100');

// 11. Workshops · 1 workshop + audience + federable · 100
t(rFull.byDim.workshops.score === 100,                               'C · workshops complet · 100');

// 12. Total full project · 100
t(rFull.total === 100,                                               'C · total 100 amb tot complet');
t(rFull.status === 'high',                                           'C · status high');
t(rFull.missing.length === 0,                                        'C · zero missing');

// ─── Casos parcials ─────────────────────────────────────────────────────

// 13. Sense intangible · value map perd 25
const noIntangible = {
    ...fullProject,
    vna_transactions: fullProject.vna_transactions.map(t => ({ ...t, type: 'tangible' })),
};
const rNoInt = q.computeQualityScore(noIntangible, { sops: fullSops, workshops: fullWorkshops, marketItems: fullMarket });
t(rNoInt.byDim.valueMap.score === 75,                                'D · sense intangibles · valueMap 75');
t(rNoInt.byDim.valueMap.missing.some(m => m.label.includes('intangible')), 'D · missing intangible reportat');

// 14. Sense cicle recíproc · perd 25
// (cadena lineal r1→r2→r3 sense cap parella A↔A inversa · 5+ tx · 1 intangible)
const noCycle = {
    ...fullProject,
    vna_transactions: [
        { id: 'tx-a-b-t',  from: 'r1', to: 'r2', deliverable: 'x', type: 'tangible'   },
        { id: 'tx-b-c-t',  from: 'r2', to: 'r3', deliverable: 'y', type: 'tangible'   },
        { id: 'tx-a-b-i',  from: 'r1', to: 'r2', deliverable: 'i', type: 'intangible' },
        { id: 'tx-a-b-t2', from: 'r1', to: 'r2', deliverable: 'z', type: 'tangible'   },
        { id: 'tx-b-c-t2', from: 'r2', to: 'r3', deliverable: 'w', type: 'tangible'   },
    ],
};
const rNoCycle = q.computeQualityScore(noCycle, { sops: fullSops, workshops: fullWorkshops, marketItems: fullMarket });
t(rNoCycle.byDim.valueMap.score === 75,                              'D · sense cicle · valueMap 75');
t(rNoCycle.byDim.valueMap.missing.some(m => m.label.toLowerCase().includes('cicle')), 'D · missing cicle reportat');

// 15. Roles sense entregable · deliverables baixa
const noDeliver = {
    ...fullProject,
    vna_transactions: fullProject.vna_transactions.map(t => ({ ...t, deliverable: '' })),
};
const rNoDel = q.computeQualityScore(noDeliver, { sops: fullSops, workshops: fullWorkshops, marketItems: fullMarket });
t(rNoDel.byDim.deliverables.score === 30,                            'D · sense deliverables · score 30 (sols owner cobertura)');

// 16. SOPs draft sense contingut · no compten
const draftSops = fullSops.map(s => ({ ...s, content: { ...s.content, body: 'too short', steps: undefined } }));
const rDraft = q.computeQualityScore(fullProject, { sops: draftSops, workshops: fullWorkshops, marketItems: fullMarket });
t(rDraft.byDim.sops.score === 0,                                     'D · SOPs draft (body curt) · 0');
t(rDraft.byDim.sops.missing.length > 0,                              'D · missing SOP reportat');

// 17. Workshop sense audience · perd 25
const noAudience = [{ id: 'w1', content: { projectId: 'p-full', accessTier: 'public' } }];
const rNoAud = q.computeQualityScore(fullProject, { sops: fullSops, workshops: noAudience, marketItems: fullMarket });
t(rNoAud.byDim.workshops.score === 75,                               'D · workshop sense audience · 75');

// 18. Workshop privat · no federable
const privateWorkshop = [{ id: 'w1', content: { projectId: 'p-full', audience: 'founders', accessTier: 'private' } }];
const rPriv = q.computeQualityScore(fullProject, { sops: fullSops, workshops: privateWorkshop, marketItems: fullMarket });
t(rPriv.byDim.workshops.score === 75,                                'D · workshop privat · 75 (no federable)');

// 19. Status middle (50-74) i baix (<50)
const partialProject = {
    id: 'p-partial', nombre: 'Partial',
    description: 'A description long enough to pass the sixty character minimum threshold here.',
    vna_roles: [{ id: 'r1', name: 'A' }, { id: 'r2', name: 'B' }],
    vna_transactions: [{ id: 'tx', from: 'r1', to: 'r2', deliverable: 'x', type: 'tangible' }],
};
const rPartial = q.computeQualityScore(partialProject);
t(rPartial.total < 50,                                               'E · projecte parcial · total < 50 (' + rPartial.total + ')');
t(rPartial.status === 'low',                                         'E · projecte parcial · status low');

// 20. Pesos · canvi de dimensió amb pes baix té efecte petit
// Test que el total respecta els pesos: si sols la landing està a 100, total = 100*20% = 20
const onlyLanding = {
    id: 'p-l', nombre: 'L',
    description: 'A description long enough to pass the sixty character minimum threshold here.',
    presentation_narrative_v1: 'narrative',
    vna_roles: [], vna_transactions: [],
};
const rOnlyL = q.computeQualityScore(onlyLanding, { marketItems: [{ id: 'm1', content: { projectId: 'p-l' } }] });
t(rOnlyL.byDim.landing.score === 100,                                'E · only landing · landing 100');
t(rOnlyL.total === 20,                                               'E · only landing · total 20 (sols pes 20%)');

// 21. statusColor / statusIcon retornen strings
t(typeof q.statusColor('high')   === 'string',                       'F · statusColor high · string');
t(typeof q.statusColor('medium') === 'string',                       'F · statusColor medium · string');
t(typeof q.statusColor('low')    === 'string',                       'F · statusColor low · string');
t(q.statusIcon('high')   === '🌟',                                   'F · statusIcon high');
t(q.statusIcon('medium') === '⚠',                                    'F · statusIcon medium');
t(q.statusIcon('low')    === '❌',                                   'F · statusIcon low');

// 22. Missing porta cta amb href + label
const someMissing = rPartial.missing.find(m => m.cta);
t(someMissing && someMissing.cta.href && someMissing.cta.label,      'F · missing items porten cta href+label');
t(someMissing && someMissing.dim,                                    'F · missing items porten dim id');

// ─── Sprint C · suggestNextDim + renderProjectSubnavHtml (navService) ──
import { suggestNextDim, renderProjectSubnavHtml, PROJECT_SUBNAV_ITEMS } from '../core/navService.js';

// 23. suggestNextDim retorna la dim amb més gain
const r23 = q.computeQualityScore(partialProject);
const next23 = suggestNextDim(r23);
t(next23 && next23.dim && typeof next23.gain === 'number',           'G · suggestNextDim retorna dim+gain');
t(next23.gain > 0,                                                   'G · partial project · gain > 0');

// 24. Tots a 100 · next null
const next24 = suggestNextDim(rFull);
t(next24 === null,                                                   'G · projecte complet · next = null');

// 25. Gain calculation · weight 30% × (100-0)/100 = 30
// valueMap (pes 30%) buit a 0 dona el màxim gain
const projectOnlyLanding = q.computeQualityScore(onlyLanding, { marketItems: [{ id: 'm1', content: { projectId: 'p-l' } }] });
const next25 = suggestNextDim(projectOnlyLanding);
t(next25.dim.id === 'valueMap',                                      'G · only-landing · next = valueMap (pes max)');
t(next25.gain === 30,                                                'G · only-landing · gain = 30 (weight×100%)');

// 26. PROJECT_SUBNAV_ITEMS conté hub + 10 tabs (sprint E afegeix Qualitat)
t(Array.isArray(PROJECT_SUBNAV_ITEMS) && PROJECT_SUBNAV_ITEMS.length === 11, 'G · 11 tabs al subnav');
t(PROJECT_SUBNAV_ITEMS[0].id === 'hub',                              'G · primera tab és hub');
t(PROJECT_SUBNAV_ITEMS[1].id === 'quality',                          'G · segona tab és quality');
t(typeof PROJECT_SUBNAV_ITEMS[0].buildHref === 'function',           'G · cada tab té buildHref()');

// 27. renderProjectSubnavHtml genera HTML amb el projecte
const subnavHtml = renderProjectSubnavHtml({
    project: fullProject,
    quality: rFull,
    pathname: '/map',
});
t(typeof subnavHtml === 'string' && subnavHtml.length > 100,         'G · renderProjectSubnavHtml retorna HTML no buit');
t(subnavHtml.includes('Full Demo'),                                  'G · subnav conté nom del projecte');
t(subnavHtml.includes('/map?project=p-full'),                        'G · subnav conté href map amb projectId');
t(subnavHtml.includes('is-active'),                                  'G · subnav marca la tab activa');
t(!subnavHtml.includes('Següent'),                                   'G · subnav score 100 NO mostra "Següent"');
t(subnavHtml.includes('Excel'),                                      'G · subnav score ≥90 mostra "Excel·lent"');

// 28. Subnav per projecte amb score baix · mostra cta "Següent"
const subnavLow = renderProjectSubnavHtml({
    project: partialProject,
    quality: r23,
    pathname: '/dashboard',
});
t(subnavLow.includes('Següent'),                                     'G · score baix · subnav mostra "Següent"');
t(subnavLow.includes('+'),                                           'G · subnav mostra gain points');

// 29. Subnav null project · retorna ""
const subnavEmpty = renderProjectSubnavHtml({});
t(subnavEmpty === '',                                                'G · sense projecte · subnav buit');

console.log('\n---\n' + pass + ' pass · ' + fail + ' fail\n');
if (fail > 0) process.exit(1);
